services:
  postgres_db:
    container_name: postgres
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - ./dbfiles:/docker-entrypoint-initdb.d
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
    networks:
      - users-network

  pgadmin4:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "1234"
    ports:
      - 80:80
    depends_on:
      - postgres_db
    networks:
      - users-network

  ms_users:
    container_name: users-m4
    build:
      context: ./ms-users-m4
      dockerfile: Dockerfile
    ports:
      - 8081:8080
    depends_on:
      - postgres_db
    networks:
      - users-network

networks:
  users-network:
    driver: bridge
